/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main.java.com.fluid;

import javax.swing.JList;
import javax.swing.JOptionPane;


/**
 * This class is the window to list all of the favorites
 *
 * @author James Kimmell <jkimmell@fluid.com>
 */
public class FavoritesWindow extends javax.swing.JFrame {
    /**
     * FavoritesWindow
     */
    private FavoritesList favorites;
    /**
     * Instance of the Add Favorite Window
     */
    private AddFavoriteWindow addFavoriteWindow;

    /**
     * Add Window Setter
     *
     * @param addFavoriteWindow
     */
    public void setAddFavoriteWindow(AddFavoriteWindow addFavoriteWindow) {
        this.addFavoriteWindow = addFavoriteWindow;
    }

    /**
     * Creates new form FavoritesWindow
     */
    public FavoritesWindow() {
        initComponents();

        //We don't want to close the application when this window close
        this.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }

    /**
     * FavoritesWindow Setter
     *
     * @param favorites
     */
    public void favorites(FavoritesList favorites) {
        this.favorites = favorites;
    }
    
    public void showAddWindow() {
        this.addFavoriteWindow.setVisible(true);
    }
    
    public JList getFavoritesList() {
        return this.favoritesDisplayList;
    }
    
    public void showFavorite (Favorite favorite) {
        this.favoriteURL.setText(favorite.getBaseUrl());
        this.favoriteUsername.setText(favorite.getUsername());
        this.favoritePassword.setText(favorite.getPassword());
    }
    
    public void emptyFavorite () {
        this.favoriteURL.setText("");
        this.favoriteUsername.setText("");
        this.favoritePassword.setText("");        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        favoritesDisplayList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        favoriteURL = new javax.swing.JTextField();
        favoriteUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        deleteFavoriteButton = new javax.swing.JButton();
        favoritePassword = new javax.swing.JPasswordField();
        addFavoriteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Favorites");

        favoritesDisplayList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        favoritesDisplayList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                favoritesDisplayListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(favoritesDisplayList);

        jLabel1.setText("URL");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        favoriteURL.setEditable(false);

        favoriteUsername.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel4.setText("Favorite");

        deleteFavoriteButton.setText("Delete Favorite");
        deleteFavoriteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFavoriteButtonActionPerformed(evt);
            }
        });

        addFavoriteButton.setText("Add Favorite");
        addFavoriteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFavoriteButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(addFavoriteButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 246, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(favoritePassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(deleteFavoriteButton))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(favoriteURL))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(favoriteUsername))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(favoriteURL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(favoriteUsername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(favoritePassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(deleteFavoriteButton)
                .addContainerGap(391, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(jScrollPane1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(addFavoriteButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void favoritesDisplayListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_favoritesDisplayListValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }
        
        Favorite favorite = (Favorite)this.favoritesDisplayList.getSelectedValue();
        
        if (favorite != null) {
            this.showFavorite(favorite);
        }
        
    }//GEN-LAST:event_favoritesDisplayListValueChanged

    private void deleteFavoriteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteFavoriteButtonActionPerformed
        Favorite favorite = (Favorite)this.favoritesDisplayList.getSelectedValue();

        int answer = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this favorite?", "Input", JOptionPane.YES_NO_OPTION);

        if (answer == JOptionPane.YES_OPTION) {
            this.emptyFavorite();
            this.favoritesDisplayList.clearSelection();
            this.favorites.remove(favorite);
        }
    }//GEN-LAST:event_deleteFavoriteButtonActionPerformed

    private void addFavoriteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFavoriteButtonActionPerformed
        addFavoriteWindow.setVisible(true);
    }//GEN-LAST:event_addFavoriteButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFavoriteButton;
    private javax.swing.JButton deleteFavoriteButton;
    private javax.swing.JPasswordField favoritePassword;
    private javax.swing.JTextField favoriteURL;
    private javax.swing.JTextField favoriteUsername;
    private javax.swing.JList favoritesDisplayList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
